apiVersion: v1
kind: Pod 
metadata: 
  name: pod2
spec:
  containers:
  - name: c1
    image: darwikdev11/ansi_server   # quay.io/openshiftlabs/simpleservice:0.5.0 
    restart: always 
    command: 
      - "/bin/bash"
      - "-c"
      - "sleep 10000"
