apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: deploy-1
spec: 
  replicas: 5
  selector:
    matchLabels:
      app: sise-deploy 
  template: 
    metadata:
      labels:
        app: sise-deploy
    spec:
      containers:
      - name: container1 
        image: quay.io/openshiftlabs/simpleservice:0.5.0
        ports: 
        - containerPort: 9876 
        env: 
        - name: SIMPLE_SERVICE_VERSION 
          value: "0.9" 
